kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/oliver006/drone-gcf

steps:
  - name: test
    image: "golang:1.14"
    environment:
      COVERALLS_TOKEN:
        from_secret: coveralls-token
    commands:
      - 'echo " ! gofmt -d *.go 2>&1 | read " | bash'
      - 'go vet ./...'
      - "go build"
      - "go test -v -covermode=atomic -cover -race -coverprofile=coverage.txt"
      - "go get github.com/mattn/goveralls"
      - "/go/bin/goveralls -v -coverprofile=coverage.txt -service=drone.io"
    when:
      event:
        - push


  - name: build-and-publish-tagged
    image: plugins/docker
    settings:
      tags: "latest,${DRONE_TAG}"
      dockerfile: ./Dockerfile
      repo: oliver006/drone-gcf
      target: release
      debug: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
